//           image:   "https://operahouse.mypinata.cloud/ipfs/image.jpg",
//           name: "Collection Title",
//           address:"Contract Address",
//           prefix: "prefix for metadata MUST BE IPFS EXAMPLE: https://operahouse.mypinata.cloud/ipfs/QmdSxQuzgDf3Bo7hgW4V41at1N11dfdjoo2fiV7CsjLPFp/",
//           addressShort:"First 8 digits of collection address 0x7f443d followed by ...",
//           collecionOwner: "address that owns the collection must match ftmscan",
//           royalty: % royalty up to 15% do not include the % symbol,
//           category:"category for future use currently all use collectibles",
//           website:"link to website and homepage",
//           discord:"use only the discord code example V6H3CQKSH6"
//           twitter: "Use only the twitter handle"

// Start symbols for audited score: FILL ★ EMPTY ☆


//----------------------TEMPLATE FOR ADDING COLLECTIONS--------------------------------------
// image: "",
// collectionBanner: "",
// collectionDescription:"",
// name: "",
// address:"",
// prefix: "https://operahouse.mypinata.cloud/ipfs/",
// collecionOwner: "",
// royalty: ,
// addressShort:"...",
// category:"",
// website:"",
// discord:"",
// twitter:"",
// trending:,
// audit:"",
// minting:,

        export const networkCollections = {
          "0xfa": [
            {
              image:"/img/collectionmain/operacommunity.jpg",
              collectionBanner:"/img/banners/operacommunity.jpg",
              collectionDescription:
              "Welcome to our Beta Community Collection. Here users are free to mint their NFTs and express their creativity using our platform.",
              name: "Opera House Community",
              address:"0x86c4764A936B0277877CB83aBf1ad79CE35C754C",
              collecionOwner: "0xCc3C8FD424737100557C132e10080226852e40eB",
              royalty: 10,
              addressShort:"0x86c476...",
              category:"Collectibles",
              website:"https://operahouse.online",
              discord:"mHtRYmd",
              twitter:"NovaFinOfficial",
              trending:true,
              audit:"Audited ★★★★★",
              minting:false,
              sellable:true,

          },
          {
              image:"/img/collectionmain/babychimpgang.jpg",
              collectionBanner:"/img/banners/babychimpgang.jpg",
              collectionDescription:"The BabyChimpGang is a collection of 1111 unique chimpanzee NFTs build on the Fantom Opera blockchain.",
              name: "Baby Chimp Gang",
              address:"0x7f9893ef9726d23e249518eaa1424677b7fed6a9",
              addressShort:"0x7f9893...",
              collecionOwner: "0xe35C2d87607Dc6816C9d0492177b4dA70a0a5ccb",
              royalty: 5,
              category:"Collectibles",
              website:"https://babychimpgang.com/",
              discord:"x7EKQdkfDm",
              twitter:"BabyChimpGang",
              trending:true,
              audit:"Audited ★★★★★",
              minting:false,
sellable:true,
          },
          {
            image:"/img/collectionmain/babychimpgangx.jpg",
            collectionBanner:"/img/banners/babychimpgangx.jpg",
            collectionDescription:"The BabyChimpGangXmas is a special collection of 863 festive chimpanzee NFTs build on the Fantom Opera blockchain.",
            name: "Baby Chimp Gang Xmas",
            address:"0x207a1521Aa373a9bd44C17fAf9e77397195B77f9",
            addressShort:"0x207a15...",
            collecionOwner: "0xe35C2d87607Dc6816C9d0492177b4dA70a0a5ccb",
            royalty: 5,
            category:"Collectibles",
            website:"https://babychimpgang.com/",
            discord:"x7EKQdkfDm",
            twitter:"BabyChimpGang",
            trending:false,
            audit:"Audited ★★★★★",
            minting:false,
sellable:true,

          },
          {
            image:"/img/collectionmain/raccoonplatoon.gif",
            collectionBanner:"/img/banners/raccoonplatoon.jpg",
            name: "Raccoon Platoon",
            collectionDescription:"Raccoon Platoon is collection of 256 randomly generated raccoon NFTs on the Fantom blockchain. Created by the Opera House Staff.",
            address:"0x9ee3479f88431040f96266c73c6949f4b694e97e",
            collecionOwner: "0x892905132Ff007bcdA44e8f1C5800A8F722ceE5F",
            royalty: 5,
            addressShort:"0x9ee347...",
            category:"Collectibles",
            website:"https://raccoonplatoon.com",
            discord:"mHtRYmd",
            twitter:"NovaFinOfficial",
            trending:true,
            audit:"Audited ★★★★★",
            minting:true,
sellable:true,
            price:"45",
            maxSupply:"256",

          },
          {
            image:"/img/collectionmain/magicats.jpg",
            collectionBanner:"/img/banners/magicats.jpg",
            collectionDescription:"When Grim descended upon our world on her paws and broom, she encountered magical kittens who were unaware that they were stuck inside human skins. Who is your inner Magicat? Official SpookySwap Genesis NFTs | 5000 Limited",
            name: "MagiCats",
            address:"0x2aB5C606a5AA2352f8072B9e2E8A213033e2c4c9",
            collecionOwner: "0x95478C4F7D22D1048F46100001c2C69D2BA57380",
            royalty: 5,
            addressShort:"0x2aB5C6...",
            category:"Collectibles",
            website:"spookyswap.finance",
            discord:"spookyswap",
            twitter:"SpookySwap",
            trending:false,
            audit:"Audited ★★★★★",
            minting:false,
sellable:true,

        },
        {
        image:"/img/collectionmain/8bit.jpg",
        collectionBanner:"/img/banners/8bit.jpg",
        collectionDescription:"Home of the Nostalgia Metaverse, 8-Bit Nostalgia's NFTs are proof of land ownership in the Metaverse.",
        name: "8Bit Nostalgia",
        address:"0x406349e0bcdf323526c11b4e987a699471142b84",  
        collecionOwner: "0x0413e238c56005ac17F60E4eBDBFC45Fe6fdb0F0",
        royalty: 7.5,
        addressShort:"0x406349...",
        category:"Games & Virtual Worlds",
        website:"https://www.8bitnostalgia.io/",
        discord:"8bitmetaverse",
        twitter:"8bit_metaverse",
        trending: false,
        audit:"Not Audited",
        minting: false,
        },
        {
          image:"/img/collectionmain/netizens.jpg",
          collectionBanner:"/img/banners/netizens.jpg",
          collectionDescription:"Netizens are in game characters that are playable in 8Bit Nostalgia Metaverse, Netizens can socialize, breed, play, and earn multiple tokens! Own your Netizen and enter our Metaverse today!",
          name: "Netizens",
          address:"0x47C414909F0c8c663DA2bf8b96592c1C6B8C4215",
          collecionOwner: "0x0413e238c56005ac17F60E4eBDBFC45Fe6fdb0F0",
          royalty: 7.5,
          addressShort:"0x47C414...",
          category:"Games & Virtual Worlds",
          website:"https://www.8bitnostalgia.io/",
          discord:"8bitmetaverse",
          twitter:"8bit_metaverse",
          trending: false,
          audit:"Not Audited",
          minting: false,
          },
          {
          image:"/img/collectionmain/minichillas.jpg",
          collectionBanner:"/img/banners/minichillas.jpg",
          collectionDescription:"Digital chinchillas exploring the Mini-Verse looking for frens or foes.",
          name: "MiniChillas",
          address:"0xC2750650CAE36385E791bB0f32E9CE568A0c66bd",
          collecionOwner: "0xeD27eFf42c32e22e78d404410cF9289DEBB270Cf",
          royalty: 7.5,
          addressShort:"0xC27506...",
          category:"Games & Virtual Worlds",
          website:"https://mint.miniverseclub.com/",
          discord:"CxRWUGSyRv",
          twitter:"MiniVerseClub",
          trending:false,
          audit:"Audited ★★★★★",
          minting:false,
sellable:true,
          },
          {
          image:"/img/collectionmain/miniguineas.jpg",
          collectionBanner:"/img/banners/miniguineas.jpg",
          collectionDescription:"555 digital guinea pigs exploring the Mini-Verse looking for frens or foes.",
          name: "MiniGuineas",
          address:"0xEc2e4e100b26015dc7DEe337b4dC5decFE28DB58",
          collecionOwner: "0xeD27eFf42c32e22e78d404410cF9289DEBB270Cf",
          royalty: 7.5,
          addressShort:"0xEc2e4e...",
          category:"Games & Virtual Worlds",
          website:"https://miniverseclub.com/",
          discord:"CxRWUGSyRv",
          twitter:"MiniVerseClub",
          trending:false,
          audit:"Audited ★★★★★",
          minting:false,
sellable:true,
          },
          {
            image:"/img/collectionmain/nftduelz.jpg",
            collectionBanner:"/img/banners/nftduelz.jpg",
            collectionDescription:"NFT Duelz is a multichain card duel platform that allows you to duel against another player, anywhere in the world! The game is very simple, you'll need a deck of 5 cards to enter a duel and the player that has the higher total amount of power points wins the duel. Mint now at www.nftduelz.games",
            name: "NFT Duelz",
            address:"0xBb447B20b6f14affd95dc7eB2347F187D0eE536E",
            prefix:"https://collection.nftduelz.games/",
            collecionOwner: "0x6298F51B5c20eDC214edBd640733224D5E1A5bDd",
            royalty: 7.5,
            addressShort:"0xBb447B...",
            category:"Games & Virtual Worlds",
            website:"https://www.nftduelz.games/",
            discord:"Z6qaEUMQmr",
            twitter:"NFTDuelz",
            trending: false,            
          audit:"Not Audited",
            minting: false,
            },
          {
            image:"/img/collectionmain/fantompocong.jpg",
            collectionBanner:"/img/banners/fantompocong.jpg",
            collectionDescription:"Victims of a mass massacre in an exotic motherland have awakened. They demand justice while haunting their killers. FantomPocong is a not-too-fun NFT collection consisting of 10,000 Pocong with unique traits. Please read the Introduction article before minting or buying. Happy hugging your Pocong!",
            name: "FantomPocong",
            address:"0x64b38cc012d21dbb58e21f0d2885e7509cdd4e99",
            collecionOwner: "0x5E335399DEeaD358Fb893f6594F2A1eDC91C340f",
            royalty: 2.5,
            addressShort:"0x64b38c...",
            category:"Collectibles",
            website:"https://fantompocong.netlify.app/",
            discord:"XAHA5XHNr7",
            twitter:"FantomPocong",
            trending:false,
            audit:"Not Audited",
            minting:true,
sellable:true,
            price:"1",
            maxSupply:"10000",

          },
          {
            image:"/img/collectionmain/rookiepenguins.jpg",
            collectionBanner:"/img/banners/rookiepenguins.jpeg",
            collectionDescription:"Rookie Penguins is a collection of 1000 uniquely and randomly NFTs stored on the Fantom Blockchain.",
            name: "Rookie Penguins",
            address:"0xA65f9b290423C667094Fe2E0f7F58f2Dfd867c4d",
            prefix:"https://www.rookiepenguins.com/api/penguin/",
            collecionOwner: "0x0F961f594450E67D78557b444b90EFF8EB7c5a34",
            royalty: 5,
            addressShort:"0xA65f9b...",
            category:"Collectibles",
            website:"https://www.rookiepenguins.com/",
            discord:"vYV99E2Gjk",
            twitter:"RookiePenguins",
            trending:false,
            audit:"Not Audited",
            minting:false,
sellable:true,

          },
          {
            image:"/img/collectionmain/roompixes.jpg",
            collectionBanner:"/img/banners/roompixes.jpg",
            collectionDescription:"Roompixes are collection of 8192 (2^13) procedurally generated pixel art rooms. Each Roompix may contain assets from collection of more than 400 items which makes every room totally unique!",
            name: "RoomPixes",
            address:"0x32e13161E30acD5CEe7919bA8B07C2543f50f936",
            prefix:"https://operahouse.mypinata.cloud/ipfs/",
            collecionOwner: "0xF264f5EF4eE1F60d199f8f442623A39D9dfcfdED",
            royalty: 0,
            addressShort:"0x32e131...",
            category:"Collectibles",
            website:"https://www.roompixes.com/",
            discord:"anDTmfEtnU",
            twitter:"roompixes",
            trending:false,
            audit:"Not Audited",
            minting:false,
sellable:true,

          },
          {
            image:"/img/collectionmain/fantomlords.jpg",
            collectionBanner:"/img/banners/fantomlords.jpg",
            name: "Fantom Lords",
            collectionDescription:
            "Fantom Lords are an epic collection of 3333 randomly generated lordly NFTs on the Fantom blockchain.",
            address:"0xfee8077c909d956E9036c2d2999723931CeFE548",
            collecionOwner: "0x4a03721C829Ae3d448bF37Cac21527cbE75fc4Cb",
            royalty: 7.5,
            addressShort:"0xfee807...",
            category:"Collectibles",
            website:"https://fantomlords.com",
            discord:"etpsxPrWpP",
            twitter:"ENRINFT",
            trending:false,
            audit:"  Not Audited",
            minting:false,
sellable:true,

          },
          {
            image:"/img/collectionmain/fantopops.jpg",
            collectionBanner:"/img/banners/fantopops.jpg",
            collectionDescription:
            "A series inspired by the Popular Funko Pops. Rarities have been set to maximize collectability. All NFTs in this collection are unique!",
            name: "FantoPops",
            address:"0x452c1249a4492c613046612cff73dcb781ebb99b",
            prefix: "https://operahouse.mypinata.cloud/ipfs/",
            collecionOwner: "0x520998840d95256243c7f8297fC417D920E16b34",
            royalty: 5,
            addressShort:"0x452c12...",
            category:"Collectible",
            website:"https://fantopops.club",
            discord:"V6H3CQKSH6",
            twitter:"FantoPops",
            trending:false,
            audit:"Not Audited",
            minting:true,
sellable:true,
            price:"5",
            maxSupply:"1000",

        },
        {
          image:"/img/collectionmain/pekbii.jpg",
          collectionBanner:"/img/banners/pekbii.jpg",
          collectionDescription:"Just love to take picture with my phone, sunset sunrise street and nature are ma best friends!",
          name: "PekbiiPhotography",
          address:"0x8bc81EeD730457b3E9A54E4fc0C470E978882810",
          prefix: "https://operahouse.mypinata.cloud/ipfs/",
          collecionOwner: "0xFbD40302703006bcA6cbBF50476441D3F765cA6c",
          royalty: 15,
          addressShort:"0x8bc81E...",
          category:"Art & Photography",
          website:"",
          discord:"",
          twitter:"Ahmd2002_",
          trending:false,
          audit:"Not Audited",
          minting:false,
sellable:true,

      },
    {
      image:"/img/collectionmain/intersasquatch.jpg",
      collectionBanner:"/img/banners/intersasquatch.jpg",
      collectionDescription:"Rare encounters from infinite dimensions! 2000 pieces out of more than 1,000,000 possible ones!",
      name: "Interdimensional Sasquatch",
      address:"0x97FE96BdC8521AC774dAD8af04149e715680Faeb",
      prefix: "https://operahouse.mypinata.cloud/ipfs/",
      collecionOwner: "0x4F16C6763D636cCcAd0aD4897085573359CAA9F2",
      royalty: 4,
      addressShort:"0x97FE96...",
      category:"Collectible",
      website:"http://intersasquatch.online",
      discord:"e74C3jZS",
      twitter:"FTM_SASQUATCH",
      trending:false,
      audit:"Not Audited",
      minting:true,
sellable:true,
      price:"3",
      maxSupply:"2000",

  },    
  {
    image:"/img/collectionmain/darthfractals.jpg",
    collectionBanner:"/img/banners/darthfractal.jpg",
    collectionDescription:"DarthFractals is a collection of 1/1 art and accompanied physical prints. Welcome to the FractalVerse where these complex 3D structures and objects are made through a combination of math, science, and an artistic twist. Exploring an endless universe of fractals I try to find inspiring or thought-provoking art I can share with you!",
    name: "DarthFractals",
    address:"0xC01261Dc40c534349718e988B77108781FbD4D97",
    prefix: "https://operahouse.mypinata.cloud/ipfs/",
    collecionOwner: "0xAA4eB173E5AaDD0463aee92158183Abf895341Bb",
    royalty: 4.5,
    addressShort:"0xC01261...",
    category:"Art & Photography",
    website:"https://www.darthfractals.art/",
    discord:"",
    twitter:"darthrevan503",
    trending:false,
    audit:"Not Audited",
    minting:false,
sellable:true,

},
{
  image:"/img/collectionmain/bubonicbastards.jpg",
  collectionBanner:"/img/banners/bubonicbastards.jpg",
  collectionDescription:"Bubonic Bastards, or $BUBOs for short, are a gamified collectible Profile Picture series. Each $BUBO generates an ERC-20 token called ($BLOOD). You can use $BLOOD to change your character's name, attack and heal your $BUBO during the Plague Pit Games, and most importantly evolve your $BUBOs.",
  name: "Bubonic Bastards",
  address:"0x9B1372e4A65d914D670f061913AD746250533b49",
  prefix: "https://buboimage-twistedtech-wtf.ipns.dweb.link/",
  collecionOwner: "0x7932B496C310C75a02701A9a6860D9F97bC8E150",
  royalty: 5,
  addressShort:"0x9B1372...",
  category:"Collectibles",
  website:"https://twistedtech.gitbook.io/bubonic-bastards/",
  discord:"VahyZCDRmB",
  twitter:"twistedtechnfts",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,

},
{
  image:"/img/collectionmain/nightmareonfantom.gif",
  collectionBanner:"/img/banners/nightmareonfantom.jpg",
  collectionDescription:"Nightmare On Fantom St. is a trick-or-treat themed dice game. Our contract uses the on-chain randomness strategy from $LOOT. Every mint is one attempt at minting a legendary. You will roll a four-sided die when you mint to determine the “Mint-Type” (Trick or Treat). Then, you roll a six-sided die to determine if your mint goes from “Common” to “Rare.” Only if you win the six-sided die roll will you roll an eight-sided die to decide whether you mint a “Legendary.” The end goal of the game is to mint a legendary before time runs out.",
  name: "Nightmare on Fantom Street",
  address:"0x44dea70be365f616f1b47346005045374e827b83",
  prefix: "https://buboimage-twistedtech-wtf.ipns.dweb.link/",
  collecionOwner: "0x7932B496C310C75a02701A9a6860D9F97bC8E150",
  royalty: 5,
  addressShort:"0x44dea7...",
  category:"Collectibles",
  website:"https://twistedtech.gitbook.io/bubonic-bastards/",
  discord:"VahyZCDRmB",
  twitter:"twistedtechnfts",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,

},
{
  image:"/img/collectionmain/fantominvaders.jpg",
  collectionBanner:"/img/banners/fantominvaders.jpg",
  collectionDescription:"The INVADERS have decided to invade The Fantomverse to steal all human habits, they were so bored and humans are so peculiar …",
  name: "Fantom Invaders",
  address:"0x8f59cD1DFD7F02DF4ab89539aD7C6a626c9C6c95",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xe16d1a2571FeCB1fCF177c818ea1F8287a755ffE",
  royalty: 5,
  addressShort:"0x8f59cD...",
  category:"Collectibles",
  website:"https://fantominvaders.netlify.app",
  discord:"nPycYq7Cec",
  twitter:"fantom_invaders",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ghosties.jpg",
  collectionBanner:"/img/banners/ghosties.jpg",
  collectionDescription:"A collection of unique hand drawn ghosts to collect, created by Danetron3030. This is a small limited collection of 50 total Ghosties, excluding Blood Souls. Collect common to very rare souls and grow your underworld for the Ghosties. Each ghost has a past and with you, a future. Holding a Ghostie includes benefits, like granting its owner gifts and whitelistings for upcoming projects.",
  name: "Ghosties",
  address:"0x6d44fd8cec6666e2080493d4f157b066c3913437",
  prefix: "",
  collecionOwner: "0x7abDEF5Eb43d74227f4B5CA253e1b202332ad044",
  royalty: 5.5,
  addressShort:"0x6d44fd...",
  category:"Collectibles",
  website:"",
  discord:"",
  twitter:"TheDanetron3030",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/stickwarrior.jpg",
  collectionBanner:"/img/banners/stickwarrior.jpg",
  collectionDescription:"GameFi...The First rule of Stick club is you don’t talk about Stick club. The second rule of Stick club is you don’t talk about Stick club.",
  name: "Stick Warrior",
  address:"0xc4B79AFCf656B98CE530C50Af8d3faC6fa945fbe",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xad4ab28fb50Cd15687c5c251df6325cCB9DD816D",
  royalty: 6,
  addressShort:"0xc4B79A...",
  category:"Games & Virtual Worlds",
  website:"https://stickwarriors.club/",
  discord:"aK5p6yA9z7",
  twitter:"TheJoker_DAO",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"5",
  maxSupply:"5000",
},
{
  image:"/img/collectionmain/natureoracle.jpg",
  collectionBanner:"/img/banners/natureoracle.jpg",
  collectionDescription:"Nature Oracle is a small collection of ~150 Oracle card NFTs. Hand-made. Nature inspired. Unique. The Art of Nature Oracle is inspired by the Spirit of Nature and the timeless tradition of divination cards. Each NFT comes with its own name, rarity level (common / uncommon / rare) and original prediction, allowing its owner to receive readings on our website natureoracle.com",
  name:"Nature Oracle",
  address:"0x600ea64f353085a0Df6fba7335086951ee90f36f",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xB22fc8e22CAc0B95b381deA7Ea86705a7d622dF0",
  royalty: 7,
  addressShort:"0x600ea6...",
  category:"Art & Photography",
  website:"https://natureoracle.com",
  discord:"",
  twitter:"NatureOracle",
  trending:false,
  audit:"Audited ★★★★★",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/lostfantomwarriors.jpg",
  collectionBanner:"/img/banners/lostfantomwarriors.jpg",
  collectionDescription:"Collection of 64×64 px Fantom Warriors . Help us find all 200 Lost Fantom Warriors within Opera!",
  name: "Lost Fantom Warriors",
  address:"0xf6c34b502ec139728eda41e372750f581e224436",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x1CD56B37aB3B5EDB64F1A8Bc845D307D83C1B086",
  royalty: 7.5,
  addressShort:"0xf6c34b...",
  category:"Collectibles",
  website:"https://www.lostftmwarrior.com",
  discord:"pBBMNjCmgW",
  twitter:"LostFtmWarriors",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/raiders.jpg",
  collectionBanner:"/img/banners/raiders.jpg",
  collectionDescription:"Raiders is a Gamefi yield farming protocol through the use of play to earn NFTs.",
  name: "Raiders",
  address:"0x65c4f2619bfe75215459d7e1f351833e7511290c",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xc2237a7Dbe9c975db3dc8d013c83E3D3919287c2",
  royalty: 0,
  addressShort:"0x65c4f2...",
  category:"Games & Virtual Worlds",
  website:"https://app.raiders-nft.com/mint",
  discord:"Cp9bs7vxMy",
  twitter:"RaidersNFT",
  trending:true,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"10",
  maxSupply:"",
},
{
  image:"/img/collectionmain/raidrelics.jpg",
  collectionBanner:"/img/banners/raidrelics.jpg",
  collectionDescription:"Raid Relics are Limited collectors edition Raiders NFTs.",
  name: "Raid Relics",
  address:"0xac7d8ac1a50f1696871fe77dc50aa8b36279dec6",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xc2237a7Dbe9c975db3dc8d013c83E3D3919287c2",
  royalty: 0,
  addressShort:"0xac7d8a...",
  category:"Games & Virtual Worlds",
  website:"https://www.Raiders-NFT.com",
  discord:"Cp9bs7vxMy",
  twitter:"RaidersNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fruityfrens.jpg",
  collectionBanner:"/img/banners/fruityfrens.jpg",
  collectionDescription:"  Fruity Frens is a community driven collection of 1,000 randomly generated NFTs on the Fantom Opera Network.",
  name: "Fruity Frens",
  address:"0xc0fa7b5debf99b529d39d22cc01594ace3d6fb30",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xa8bb7718A55C00668b8B6Fe2a542d217b2148c57",
  royalty: 7,
  addressShort:"0xc0fa7b...",
  category:"Art & Photography",
  website:"https://www.fruityfrens.club",
  discord:"BC3JqCeDm9",
  twitter:"fruityfrens",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"15",
  maxSupply:"1000",
},
{
  image:"/img/collectionmain/ftmquestweapons.jpg",
  collectionBanner:"/img/banners/ftmquestweapons.jpg",
  collectionDescription:"Fantom Quest Weapons is a collection of items that will keep you safe on your adventures. It is dangerous to go alone, so take one of these.",
  name: "Fantom Quest Weapons",
  address:"0x7281F454e1631E0Ed7E1eD509FBEFF87d0ae9b0f",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x0d1e8bf3ac954d1328A1641E06104212041D6948",
  royalty: 7,
  addressShort:"0x7281F4...",
  category:"Games & Virtual Worlds",
  website:"https://www.fantomquest.com",
  discord:"9N9rnPcwUq",
  twitter:"FTMQuest",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,

},
{
  image:"/img/collectionmain/ftmmunks.jpg",
  collectionBanner:"/img/banners/ftmmunks.jpg",
  collectionDescription:"Welcome to the first collection inside the MUNKVERSE. This is your gateway to this amazing journey. Claim your MUNK. Stay safe. Mint a MUNK: get a profile-pic with cool shapes and colors. Hold your MUNK: get some cool game-asset-like NFTs. Hold everything: get a strategy-game.",
  name: "Fantom Munks",
  address:"0x7e72f05b8cd0860a83a6b27d3d80bd3b3e440c27",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x254f9595ca1c2e567c51d5b44f0f43cf485ef154",
  royalty: 7,
  addressShort:"0x7e72f0...",
  category:"Art & Photography",
  website:"https://www.munksnft.com/",
  discord:"THKSHkJA87",
  twitter:"munks_nft",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"1",
  maxSupply:"10000",
},
{
  image:"/img/collectionmain/cyberfantoms.jpg",
  collectionBanner:"/img/banners/cyberfantoms.jpg",
  collectionDescription:"1500 Cyber Fantoms, now hold2earn!",
  name: "Cyber Fantoms",
  address:"0xcb0ff14cac96add86223c8c7e8a6129cd92919ab",
  collecionOwner: "0x54755999d5298202f2221f6b3f81237c072fe1f7",
  royalty: 7.5,
  addressShort:"0xcb0ff1...",
  category:"Collectibles",
  website:"https://cyber.fantoms.art",
  discord:"fantoms",
  twitter:"FantomsOpera",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/intergalacticworld.jpg",
  collectionBanner:"/img/banners/intergalacticworld.jpg",
  collectionDescription:"We found life in space, with AI-Generated Intergalactic World Collection we show you all of our findings in outer space, go now and brag because aliens do EXIST… here is the proof.",
  name: "Intergalactic World",
  address:"0x345914fdd7a4091ef6C6bF74ed88D6AB24908514",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x4504e2855d53939A127C8FCac690a70e1A9A9f58",
  royalty: 2.5,
  addressShort:"0x345914...",
  category:"Art & Photography",
  website:"",
  discord:"gNAvKUDs",
  twitter:"interNFTworld",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/froggedfrogz.jpg",
  collectionBanner:"/img/banners/froggedfrogz.jpg",
  collectionDescription:"Frogged Frogz are personalized Frog Token NFTs made with love by StarLord, the official artist of Frog Token. The 100 Frogged Frogz featured in this collection are made in reference to everyday life, religion & pop culture.",
  name: "Frogged Frogs",
  address:"0x4fAfD32e22E2a408d0e03dcBC58ED017CF1Aae27",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x03ba6F844B821024627DA7A37E48ba8385AEB823",
  royalty: 10,
  addressShort:"0x4fAfD3...",
  category:"Art & Photography",
  website:"https://frog-dapp.vercel.app",
  discord:"NCJbjGNR",
  twitter:"StarLord_FTM",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/roguecrocs.jpg",
  collectionBanner:"/img/banners/roguecrocs.jpg",
  collectionDescription:"The original crocs, 10,000 crocs taking over the FTM landscape. Also giving in game utility on our upcoming game, build your collection to flex in game.",
  name: "Rogue Crocs",
  address:"0x1Ac92647dA673621EC66bf76F0bB112a9A3D8F64",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xDD44fABE409a25d9e02361A0f1025299F25f7A43",
  royalty: 5,
  addressShort:"0x1Ac926...",
  category:"Collectibles",
  website:"www.roguecrocs.com",
  discord:"Xgcb65bFTp",
  twitter:"crocsrogue",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fantomjersey.jpg",
  collectionBanner:"/img/banners/fantomjersey.jpg",
  collectionDescription:"One of the only NFT projects providing real-world utility. Receive a matching jersey with every 1st time NFT purchase including free shipping. Wear them with pride, raise awareness for our beloved FTM, collect them all and stay tuned for future releases. One of the only NFT projects providing real-world utility. Receive a matching jersey with every 1st time NFT purchase including free shipping. Wear them with pride and raise awareness for our beloved FTM. Order yours while the FTM price is still low. Accepting orders, get yours while FTM is still low. Jerseys will ship out from Valentine's day onwards. Join our discord for retrieval details.",
  name: "Fantom Jerseys",
  address:"0x62bcF34fe7868406a505E59697e76914fb0a460a",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0x55Ab844F1CAddc57b412E83892616e3d8cb3DB63",
  royalty: 3.3,
  addressShort:"0x62bcF3...",
  category:"Collectibles",
  website:"https://fantomjerseys.com/",
  discord:"duh6ex6N",
  twitter:"ftm_nft",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fantomsquad.jpg",
  collectionBanner:"/img/banners/fantomsquad.jpg",
  collectionDescription:"The FantomSquad is a collection of 2,600 Bats with hundreds of elements inspired by daily life, mythology, History and much more. Each Squad member is unique with their own combination of elements giving each bat their own personal story. Supporters of the project will be able to vote on the future of the project and will have a direct impact on the development of the FantomSquad multiverse.",
  name: "FantomSquad",
  address:"0xb680b9861f73B30d86BdC248376d9566ade3FD35",
  collecionOwner: "0x14d254121d0a46463DdcaCA5767c3D6C911249C7",
  royalty: 5,
  addressShort:"0xb680b9...",
  category:"Collectibles",
  website:"https://www.fantomsquad.com/",
  discord:"uUe6H9F7",
  twitter:"FantomSquad_NFT",
  trending:true,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"52",
  maxSupply:"2500",
},
{
  image:"/img/collectionmain/fantomsquadmp.jpg",
  collectionBanner:"/img/banners/fantomsquad.jpg",
  collectionDescription:"The FantomSquad is a collection of 2,600 Bats with hundreds of elements inspired by daily life, mythology, History and much more. Each Squad member is unique with their own combination of elements giving each bat their own personal story. Supporters of the project will be able to vote on the future of the project and will have a direct impact on the development of the FantomSquad multiverse.",
  name: "FantomSquad Mint Passes",
  address:"0x0358382CA3455f7c9cD9B0524C9CCf7ABC4a7350",
  collecionOwner: "0x14d254121d0a46463DdcaCA5767c3D6C911249C7",
  royalty: 5,
  addressShort:"0x035838...",
  category:"Collectibles",
  website:"https://www.fantomsquad.com/",
  discord:"uUe6H9F7",
  twitter:"FantomSquad_NFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fantomsquadgmp.jpg",
  collectionBanner:"/img/banners/fantomsquad.jpg",
  collectionDescription:"The FantomSquad is a collection of 2,600 Bats with hundreds of elements inspired by daily life, mythology, History and much more. Each Squad member is unique with their own combination of elements giving each bat their own personal story. Supporters of the project will be able to vote on the future of the project and will have a direct impact on the development of the FantomSquad multiverse.",
  name: "FantomSquad Gold Minting Pass",
  address:"0x4B128fcEA7F8fE4EA7591584554AdEB309BA0a77",
  collecionOwner: "0x14d254121d0a46463DdcaCA5767c3D6C911249C7",
  royalty: 5,
  addressShort:"0x4B128f...",
  category:"Collectibles",
  website:"https://www.fantomsquad.com/",
  discord:"uUe6H9F7",
  twitter:"FantomSquad_NFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ftmvoid.jpg",
  collectionBanner:"/img/banners/ftmvoid.jpg",
  collectionDescription:"Void comes from different world. they are finding a new home and found Fantom. but no one knows where they came from, from another planet? Or from another galaxy? Or are they the form of the galaxy itself?",
  name: "VOID FTM",
  address:"0xEE188818448cbCC9b1f28851810854989cA55119",
  collecionOwner: "0xFbD40302703006bcA6cbBF50476441D3F765cA6c",
  royalty: 10,
  addressShort:"0xEE1888...",
  category:"Collectibles",
  website:"",
  discord:"",
  twitter:"Ahmd2002_",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/roosterz.jpg",
  collectionBanner:"/img/banners/roosterz.jpg",
  collectionDescription:"The Roosterz is a 5000 collection generative project living on the Fantom blockchain.",
  name: "The Roosterz",
  address:"0xe5fa7f426baa3ae07fb67b969933debda28a6667",
  collecionOwner: "0x2BcD7784b70Ca9E5eEFAdE7EcA321f5A90D748DA",
  royalty: 7.5,
  addressShort:"0xe5fa7f...",
  category:"Collectibles",
  website:"https://www.theroosterz.com",
  discord:"hq7P6st3AJ",
  twitter:"TheRoosterzFTM",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"15",
  maxSupply:"5000",
},
{
  image:"/img/collectionmain/cryptowormz.jpg",
  collectionBanner:"/img/banners/cryptowormz.jpg",
  collectionDescription:"CryptoWormz is a fun NFT project made for degens, created by degens. It's a collection of 7777 Wormz with unique personalities and qualities. Some Wormz have been digging the world longer than others and some have been lucky enough to find exciting items of different rarities. Legends say that some of the Wormz have accidentally eaten radioactive dung turning them green and grown shells, madness! Season 2 Coming",
  name: "CryptoWormz",
  address:"0x74D3736377fd0251c19b2b77288Cea6D3Ad87578",
  collecionOwner: "0x1231c467621A3E6C4D179B7ECece57711aba24aD",
  royalty: 0,
  addressShort:"0x74D373...",
  category:"Collectibles",
  website:"https://cryptowormz.fi",
  discord:"PJ3zCpfwwP",
  twitter:"crypto_wormz",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/wtfboats.jpg",
  collectionBanner:"/img/banners/wtfboats.jpg",
  collectionDescription:"WTFBoats is a limited set of 111 boats that could originally only be caught in the WhatTheFish preseason. Boat holders are entitled to revenue share and boats can be driven by their owners on Lake Minnow at wt.fish/game",
  name: "WTFBoats",
  address:"0x9794375bbde06e0654d50e87701bbadfae6be2c4",
  collecionOwner: "0xcef6616dead86726c321e0fc81bd7d9e6ba2b49c",
  royalty: 7.5,
  addressShort:"0x979437...",
  category:"Collectibles",
  website:"https://wtfish.io",
  discord:"wtfish",
  twitter:"WhatTheFishNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fantomblobs.jpg",
  collectionBanner:"/img/banners/fantomblobs.jpg",
  collectionDescription:"Fantom Blobs is a collection of 333 Blobs on Fantom. We are focused on using community for growth. The tight community of blobs have some cool traits such as eth destroyer , 1000 ftm , and a 420 joint some work for fantom and very few are Andre's! Holders will receive airdrop of the token used in our gamfi aspect and may have WL to mint the 3d collection!",
  name: "Fantom Blobs",
  address:"0xC46CF2D62eB6302d588A725871EEE4Cb9684Ac73",
  collecionOwner: "0xE7a9635BB381725F7B69b6344b3d0b2e73A87376",
  royalty: 7,
  addressShort:"0xC46CF2...",
  category:"Collectibles",
  website:"https://sites.google.com/view/fantomblobshome/page",
  discord:"n6pWTM4jVz",
  twitter:"BlobsFantom",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"20.5",
  maxSupply:"333",
},
{
  image:"/img/collectionmain/weaponizedcountries.jpg",
  collectionBanner:"/img/banners/weaponizedcountries.jpg",
  collectionDescription:"Taking inspiration from our personal doodles as kids - Weaponized Countries is a GameFi NFT collection on Fantom of randomized countries featuring 500+ unique weapons and traits!",
  name: "Weaponized Countries",
  address:"0xc031b7793f17100e9b7ad369ca05e5ec8a0f5b5c",
  collecionOwner: "0x3f6b955bc6c879d00cea84cfdc59c7091ea90720",
  royalty: 5,
  addressShort:"0xc031b7...",
  category:"Trading Cards",
  website:"https://weaponizedcountriesnft.com",
  discord:"dQYYZgHYym",
  twitter:"WCNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/wtffish.jpg",
  collectionBanner:"/img/banners/wtffish.jpg",
  collectionDescription:"WhatTheFish is a collection of 10,000 mutated fish that reside in Lake Minnow. The first full-scale collection to utilize the new gamified minting system developed by the WhatTheFish team. Collectors of WhatTheFish are eligible for the Fish & Game Warden`s bounty/lottery program, where different traits are selected each week, entitling holders who own fish with those traits to claim FTM rewards!",
  name: "WhatTheFish",
  address:"0xa2ed7b7b54302cf3d1689cfb4177b4b7eaa50b37",
  prefix: "https://operahouse.mypinata.cloud/ipfs/",
  collecionOwner: "0xcef6616dead86726c321e0fc81bd7d9e6ba2b49c",
  royalty: 7.5,
  addressShort:"0xa2ed7b...",
  category:"Collectibles",
  website:"http://wt.fish",
  discord:"wtfish",
  twitter:"WhatTheFishNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/degensunder.jpg",
  collectionBanner:"/img/banners/degensunder.jpg",
  collectionDescription:"1500×500 Banner style images for your Twitter profile etc. - Frogs? Check - Crusty Unisocks? Check - McDonalds hat? Check -- See what else you can find 0.0",
  name: "Degens Under My Bed",
  address:"0xF25D2f52D4de560E7206610591ceC48b9De991C8",
  collecionOwner: "0x6Ce00651DB0DF8752Bb408edAf8f6b83259567F0",
  royalty: 3.3,
  addressShort:"0xF25D2f...",
  category:"Art & Photography",
  website:"https://dumb.pro/",
  discord:"r7nCZEJRNQ",
  twitter:"DUMBFTM",
  trending:false,
  audit:"Audit in Progress",
  minting:true,
sellable:true,
  price:"5",
  maxSupply:"7777",
},
{
  image:"/img/collectionmain/strangemonsters.jpg",
  collectionBanner:"/img/banners/strangemonsters.jpg",
  collectionDescription:"Strange Monster is a collection of 1113 weird NFTs, inspired by pop culture and weird stuff.",
  name: "Strange Monsters",
  address:"0xae84001ad422c494ee80630a6c03d7a12935610a",
  collecionOwner: "0xB6498b4CbB4eCe103cEf757E0a5E7c244325817f",
  royalty: 5,
  addressShort:"0xae8400...",
  category:"Art & Photography",
  website:"https://stm.fantomlouvre.art",
  discord:"B3xqJQFVW8",
  twitter:"St_MonstersNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ftmapeclub.jpg",
  collectionBanner:"/img/banners/ftmapeclub.jpg",
  collectionDescription:"Fantom Ape Club is a collection of 1,000 unique Fantom Ape NFTs – digital collectibles living on the Fantom blockchain. NFT holders are club members of an elite club – The Fantom Ape Club.",
  name: "Fantom Ape Club",
  address:"0x68ac26bdcf64ce8374aadd21ee0574ee25ace9cc",
  collecionOwner: "0x215796688D7da71D1cbc6FD64A3049CA80117C22",
  royalty: 5,
  addressShort:"0x68ac26...",
  category:"Collectibles",
  website:"",
  discord:"wYnWdryq",
  twitter:"FantomApeClub",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ftmzoo.jpg",
  collectionBanner:"/img/banners/ftmzoo.jpg",
  collectionDescription:"Please don't feed the animals.",
  name: "Fantom Zoo",
  address:"0xBe5b10f7AB643B39E8111f25ec3C504eEd7f8F5C",
  collecionOwner: "0x4F16C6763D636cCcAd0aD4897085573359CAA9F2",
  royalty: 2,
  addressShort:"0xBe5b10...",
  category:"Collectibles",
  website:"",
  discord:"N6CzAKM5",
  twitter:"FTM_Zoo",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/llamaguild.jpg",
  collectionBanner:"/img/banners/llamaguild.jpg",
  collectionDescription:"Llama Wizard is one of 1000 uniquely and programmatically generated Llamas. They belong to an ancient guild of wizards and live in a world of fantasy and magic. A minority of them even reached the highest level of a wizard called Paragon!",
  name: "Guild of Llamas",
  address:"0xe547b2ff35910e56a4edc8b32647bdc1a4fe5646",
  collecionOwner: "0x93061bbe41d928D53A7FD7a23D849478a8C9C482",
  royalty: 10,
  addressShort:"0xe547b2...",
  category:"Collectibles",
  website:"https://guildofllamas.com",
  discord:"5wQcxEFEm9",
  twitter:"GuildofLlamas",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"10",
  maxSupply:"1000",
},
{
  image:"/img/collectionmain/gnartist.jpg",
  collectionBanner:"/img/banners/gnartist.jpg",
  collectionDescription:"Special 1:1 hand-drawn Gnarwhals created to celebrate the release of Gnarwhals.ftm.",
  name: "The Gnartist",
  address:"0x36448a360e78d333C39d032bfE25572C31097eCF",
  collecionOwner: "0xA77600A3efDC8E071B6acfc85177552f2f427D92",
  royalty: 7,
  addressShort:"0x36448a...",
  category:"Art & Photography",
  website:"https://medium.com/@FantomGnarwhals",
  discord:"J9ywSU8rkg",
  twitter:"ftmgnarwhals",
  trending:false,
  audit:"Audited ★★★★★",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/bitdaemon.gif",
  collectionBanner:"/img/banners/bitdaemon.jpg",
  collectionDescription:"BitDaemons are a collection of demonic interstellar interlopers that call Fantom Opera their home. Of the thousand-strong horde that attempted the transit to Sol, just 345 arrived safely. Verified custodianship of one or more BitDaemons grants DaemonDAO membership.",
  name: "BitDaemons",
  address:"0xbea7c3f2d91a9c6fd7f5aa9c803d4c31c1db8db9",
  collecionOwner: "0x44f750eB065596c150B3479B1DF6957da300a332",
  royalty: 5,
  addressShort:"0xbea7c3...",
  category:"Collectibles",
  website:"https://bitdaemons.space",
  discord:"Hq2HYMMdTh",
  twitter:"bitdaemons",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/painthuffing.jpg",
  collectionBanner:"/img/banners/painthuffing.jpg",
  collectionDescription:"You’re 10 years old, it’s Saturday morning and you just woke up…you get out of bed in your G.I Joe jammies, pour yourself a bowl of your favorite cereal and turn on the tube. It’s time to binge watch some cartoons! You don’t know it yet, but this is as good as it gets. Ever wonder…if only you had a can of spray paint and a plastic bag to go along with that? Well you don’t have to wonder anymore, sit back and enjoy some Saturday Morning Paint Huffing Sessions",
  name: "Saturday Morning Paint Huffing Sessions",
  address:"0x3d1034e6732bfd40e2102146a3cd7d0b2d717eca",
  collecionOwner: "0x205607846698d4b8464FF0f6aab4a9a64b15839e",
  royalty: 5,
  addressShort:"0x3d1034...",
  category:"Art & Photography",
  website:"https://www.instagram.com/mazochist_laf/",
  discord:"hpbNAWefyd",
  twitter:"Mazochist_LAF",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ogsloth.jpg",
  collectionBanner:"/img/banners/ogsloth.jpg",
  collectionDescription:"866 SlothOGs",
  name: "OGs – A Slothtopia Collection",
  address:"0x612dd7b8793949bb7539f7226ef68dc9dd6a5646",
  collecionOwner: "0x5c25f3e763d567e7cbD791141f645D86Dd11c437",
  royalty: 7,
  addressShort:"0x612dd7...",
  category:"Art & Photography",
  website:"https://www.slothtopia.io",
  discord:"BjxmSBfJQx",
  twitter:"slothtopianft",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/mowsepack.jpg",
  collectionBanner:"/img/banners/mowsepack.jpg",
  collectionDescription:"MowsePack is a collection of 10,000 Mowse friends found on Fantom Opera. Mowse can own and wear fully on-chain assets, as well as, be used to stake to acquire additional assets.",
  name: "MowsePack",
  address:"0x0b896c9c8d12d0d4cd39d716b84cdde22ad2c3ea",
  collecionOwner: "0x1EF411E11fBb23000a50d198B5226A80f7E9F3AF",
  royalty: 0,
  addressShort:"0x0b896c...",
  category:"Collectibles",
  website:"https://mowsepack.com/home",
  discord:"8ExT4bx9AG",
  twitter:"MowsePack",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/supaorgn.jpg",
  collectionBanner:"/img/banners/supafnd.jpg",
  collectionDescription:"Unidentified SUPA Organism that reveals either a SUPACell or Virus NFT when identified. The first NFT that will lead to enabling players to farm Mutation Points(MP) and be part of SUPA Foundation's Metaverse(SUPAVerse).",
  name: "SUPA Organism",
  address:"0xb36949c92d84dfba03115a388e59fd881d0a9735",
  collecionOwner: "0xFFb41ebd2E7a5A91381D2975Da24e6cE5fd54738",
  royalty: 7.5,
  addressShort:"0xb36949...",
  category:"Games & Virtual Worlds",
  website:"https://portal.supa.foundation",
  discord:"7zP4fs3U3N",
  twitter:"SupaFoundation",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
},
{
  image:"/img/collectionmain/supav.jpg",
  collectionBanner:"/img/banners/supafnd2.jpg",
  collectionDescription:"SUPA Foundation virus experiment. Identified SUPA Organism that appear to be a Virus that enables NFT Farming & utility. A playable Hero in the SUPAVerse.",
  name: "SUPA Virus",
  address:"0xe186a363691fda04423d84689ae44995070c9b6e",
  collecionOwner: "0xFFb41ebd2E7a5A91381D2975Da24e6cE5fd54738",
  royalty: 7.5,
  addressShort:"0xe186a3...",
  category:"Games & Virtual Worlds",
  website:"https://portal.supa.foundation",
  discord:"7zP4fs3U3N",
  twitter:"SupaFoundation",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
},
{
  image:"/img/collectionmain/supacel.jpg",
  collectionBanner:"/img/banners/supacel.jpg",
  collectionDescription:"SUPA Foundation SUPACell experiment. Identified SUPA Organism that appear to be a SUPACell that enables NFT Farming & utility. A playable Hero in the SUPAVerse.",
  name: "SUPACell",
  address:"0x1c3e92b4e9dccb4cd1c94dd0ba6eb93835fc8a45",
  collecionOwner: "0xFFb41ebd2E7a5A91381D2975Da24e6cE5fd54738",
  royalty: 7.5,
  addressShort:"0x1c3e92...",
  category:"Games & Virtual Worlds",
  website:"https://portal.supa.foundation",
  discord:"7zP4fs3U3N",
  twitter:"SupaFoundation",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
},
{
  image:"/img/collectionmain/fantomboy.jpg",
  collectionBanner:"/img/banners/fantomboy.jpg",
  collectionDescription:"FANTOM BOY is a collection of 2,222 randomly generated NFTs that exist on Fantom (FTM) Blockchain. Unique and original artwork illustrated by Visionary Boy.",
  name: "Fantom Boy by Visionary Boy",
  address:"0x8F77400a76B38e9A359b60c4cc3C295d80C60A6f",
  collecionOwner: "0x222aBd1cF0217736E49A99755C41EfcbB0c41568",
  royalty: 6,
  addressShort:"0x8F7740...",
  category:"Art & Photography",
  website:"https://visionaryboy.com",
  discord:"g92CVDRkbE",
  twitter:"FantomBOYbyVB",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/fortunatefox.jpg",
  collectionBanner:"/img/banners/fortunatefox.jpg",
  collectionDescription:"Fantom Fortunate Fox is a collection of 1,110 randomly generated NFTs that exist on Fantom (FTM) Blockchain. Unique and original artwork created by NFT100 community. MAY FORTUNE BE WITH YOU!",
  name: "Fantom Fortunate Fox",
  address:"0x5B0B061709C1CDFBF83b720d70b336319aDC750c",
  collecionOwner: "0x8a6791e987F6ED548C4B9141B26e8757d528b932",
  royalty: 6,
  addressShort:"0x5B0B06...",
  category:"Art & Photography",
  website:"https://fantomfortunatefox.com",
  discord:"",
  twitter:"Nft100_digital",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/koalanft.jpg",
  collectionBanner:"/img/banners/koalanft.jpg",
  collectionDescription:"We are not just a NFT project, but a family of Koala Lovers! Our goal is to donate to non-profit organizations that support and safeguard the ecosystem necessary to protect Koalas. Amicable koala is our first nft collection and and is made up of 100 exclusive works. who hold an Amicable Koala receive an items from hand-made 3D collection will be delivered once all Amicable Koala Collection is sold. Get ready to feel positive vibes with our amazing community.",
  name: "Amicable Koala",
  address:"0x3d41cf7df8cb8ff3ce51254f59b0cf41849ca69d",
  collecionOwner: "0xC6CD391F4104C9780E52BB046F87374D67cA0cB4",
  royalty: 3,
  addressShort:"0x3d41cf...",
  category:"Collectibles",
  website:"https://koalanft.art",
  discord:"WE2vnNwxTn",
  twitter:"AmicableKoala",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/astrokid.jpg",
  collectionBanner:"/img/banners/astrokid.jpg",
  collectionDescription:"3333 Astrokids navigating their way through Fantom, Avalanche, and Matic. Inspired by the nostalgia of 80s and 90s cartoons and comics with the styling of Australian neo-pop artist Josh Thorsen, founder of Teens On Acid, Astrokids are like no other project you've seen before.",
  name: "Astrokid",
  address:"0x3d7E7157459A352ada13ed8dA1Ba54a08A883965",
  collecionOwner: "0x7ABCD5a3f77553a87f6a98b3D49bd559ae8B8329",
  royalty: 6,
  addressShort:"0x3d7E71...",
  category:"Art & Photography",
  website:"https://astrokidtoa.com/",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/magafrens.jpg",
  collectionBanner:"/img/banners/magafrens.jpg",
  collectionDescription:"The MAGA Frens are a group of degenerate deplorables that stormed the American Capitol building in the most deadly insurrection in American History. The damage and chaos was so severe it created a big bang and turned the f**kers into cartoon characters in NFT land. -Disclaimer- The views expressed in this series do not reflect the official policy or position of the Opera House Staff",
  name: "MAGA Frens",
  address:"0x67Be56c53d1b0f3D3590E71186B3bA6124229e66",
  collecionOwner: "0x6BFa87A4eD3cA7bC8805bb5575344Cab4D224e4E",
  royalty: 5,
  addressShort:"0x67Be56...",
  category:"Collectibles",
  website:"https://magafrens.com",
  discord:"b9VhYU4yzb",
  twitter:"MAGAFrens",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"12",
  maxSupply:"5000",
},
{
  image:"/img/collectionmain/bobblehead.mp4",
  collectionBanner:"/img/banners/bobbleheads.jpg",
  collectionDescription:"This NFT can be exchanged on our minter for a random uninted Bobblehead once the pre-sale is live. Head over to https://www.bobbleheads.xyz/ to claim it!",
  name: "Bobble Head Mint Pass",
  address:"0x25511cbb2443AaC2D9C2484553d48061a55a3CCe",
  collecionOwner: "0x070c086e5003C17A308bCec94526690846A6CA26",
  royalty: 0,
  addressShort:"0x25511c...",
  category:"Collectibles",
  website:"https://www.bobbleheads.xyz/",
  discord:"cH45DuEEgf",
  twitter:"BobbleHeadsNFT",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/creaturesofthecave.jpg",
  collectionBanner:"/img/banners/creaturesofthecave.jpg",
  collectionDescription:"The Creatures of the Cave by Potluck Protocol and PlotTwist",
  name: "Creatures of the Cave",
  address:"0xDAC2031173c07BD622759051Df373b708A1acbcE",
  collecionOwner: "0xA6F29Ab1Bf8c731Bc99E5CBacDF4F46409BABa49",
  royalty: 6,
  addressShort:"0xDAC203...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/strangeones.jpg",
  collectionBanner:"/img/banners/strangeones.jpg",
  collectionDescription:"1080 Strange Ones. They come from the outer realms, invading the Fantom Block Chain. Do they have good intentions? Only time will tell.",
  name: "Strange Ones",
  address:"0x954dBf7f372C12283f5c5feAe11ea3652Eb73352",
  collecionOwner: "0xA6F29Ab1Bf8c731Bc99E5CBacDF4F46409BABa49",
  royalty: 6,
  addressShort:"0x954dBf...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/potluckpigs.jpg",
  collectionBanner:"/img/banners/potluckpigs.jpg",
  collectionDescription:"Potluck Pigs are 1080 unique pigs living on the Fantom blockchain. Potluck Pigs bring you prosperity through their energy. HODL and we are going to make it.",
  name: "Potluck Pigs",
  address:"0x5439232D0F01F53BdEAbE3a8f19588efdfBf9c64",
  collecionOwner: "0xA6F29Ab1Bf8c731Bc99E5CBacDF4F46409BABa49",
  royalty: 6,
  addressShort:"0x543923...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/squadllama.jpg",
  collectionBanner:"/img/banners/squadllama.jpg",
  collectionDescription:"820 Bot Squad of Llamas that are taking over the Fantom Network",
  name: "Bot Squad Llamas",
  address:"0x0C448D0eA6Ef8ccda75ad4BBA4A7Ea59EbbeAC66",
  collecionOwner: "0x48407950C0A25544e9F50BF9EE57E90Ae7649B3e",
  royalty: 6,
  addressShort:"0x0C448D...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/psychrev.jpg",
  collectionBanner:"/img/banners/psychrev.jpg",
  collectionDescription:"1080 Psychedelic Faces. Humanity, through escapism, has turned to psychedelic drugs and this in turn is how they now see themselves.",
  name: "Psychedelic Revolution",
  address:"0x6e61144e7123f5936B1f299553f2c4C4fF3E2acE",
  collecionOwner: "0x57C180EE93153dC01Be22C50a09C51E02Fa2634C",
  royalty: 6,
  addressShort:"0x6e6114...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/bobblehead.jpg",
  collectionBanner:"/img/banners/bobbleheads.jpg",
  collectionDescription:"Each unique Bobblehead doubles up as your membership to the Bobblehead Club with special perks and benefits alongside the utility that will be unveiled in our roadmap. Visit: https://www.bobbleheads.xyz for more details.",
  name: "Bobbleheads",
  address:"0x8a89c505d174B056A35faF5d6c712ced921E7B48",
  collecionOwner: "0x070c086e5003C17A308bCec94526690846A6CA26",
  royalty: 5,
  addressShort:"0x8a89c5...",
  category:"Collectibles",
  website:"https://www.bobbleheads.xyz",
  discord:"cH45DuEEgf",
  twitter:"BobbleHeadsNFT",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"20",
  maxSupply:"10000",
},
{
  image:"/img/collectionmain/angryoctos.jpg",
  collectionBanner:"/img/banners/angryoctos.jpg",
  collectionDescription:"These Octos are ANGRY! Angry they are just now being minted, Angry that FTM isnt $100 yet, and Angry at all the nonstop FUD.",
  name: "Angry Octos",
  address:"0xE8Af837e2F8ab1e310990b9D362C34D897F2b0Af",
  collecionOwner: "0xBc622C6bcc9200c68d525AdF5c8b1B9C3d1C6DE3",
  royalty: 2.5,
  addressShort:"0xE8Af83...",
  category:"Collectibles",
  website:"https://linktr.ee/hashy_jim",
  discord:"YnReZtZ3Ex",
  twitter:"hashy_jim",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/hashbyjim.jpg",
  collectionBanner:"/img/banners/hashbyjim.jpg",
  collectionDescription:"Things that don't quite fit anywhere else. Nothing but the Hashiest of Hash here. -Jim",
  name: "Hash By Jim",
  address:"0x2371B3e32A66Fd33713Ef1Fe9F97576b6Cb3fA7e",
  collecionOwner: "0xBc622C6bcc9200c68d525AdF5c8b1B9C3d1C6DE3",
  royalty: 5,
  addressShort:"0x2371B3...",
  category:"Art & Photography",
  website:"https://linktr.ee/hashy_jim",
  discord:"YnReZtZ3Ex",
  twitter:"hashy_jim",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/creepers.jpg",
  collectionBanner:"/img/banners/creepers.jpg",
  collectionDescription:"Creepers are all around you. Have you ever felt like you're being watched even when completely alone? I'll let you in on a little secret, you aren't alone. While invisible to the human eye, Creepers are all around us. Through experimental (and dubiously acquired) means I am here to finally shed some light on Creepers and bring awareness to their presence. Most are harmless, merely 'creeping' wherever they find most comfortable there are some Creepers out there however, who want nothing more than to do evil. Though few and far between a Sinister Creeper will surely ruin your chill vibes..",
  name: "Creepers",
  address:"0x46c1c404829ceE64B1AdAc76cbaFdEC0e26dD03E",
  collecionOwner: "0xBc622C6bcc9200c68d525AdF5c8b1B9C3d1C6DE3",
  royalty: 6.5,
  addressShort:"0x46c1c4...",
  category:"Art & Photography",
  website:"https://linktr.ee/hashy_jim",
  discord:"YnReZtZ3Ex",
  twitter:"hashy_jim",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/boxedgen.jpg",
  collectionBanner:"/img/banners/boxedgen.jpg",
  collectionDescription:"Dark Matter DeFi presents the Boxed Generals Series! Now you can own your very own Alien. Mint your General and lead your forces to victory! Can be staked in our Staking Pools to earn DMD!",
  name: "Boxed Generals",
  address:"0x10fa5F0dE00c788C11489308f67922022862b698",
  collecionOwner: "0x365e82adAD2C86D38Bec033be04768c8eCd108e4",
  royalty: 0,
  addressShort:"0x10fa5F...",
  category:"Collectibles",
  website:"https://darkmatterdefi.com",
  discord:"VWFVkEfACd",
  twitter:"darkmatterdefi",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ddfounders.jpg",
  collectionBanner:"/img/banners/ddfounders.jpg",
  collectionDescription:"The Founders Token (FT) is the first Dark Matter NFT awarded to early adopters, community members, volunteers, and the team. The FT NFT holders get a lot of special perks like access to private chat rooms and token air drops. It can also be staked in our NFT Staking Pool to earn more tokens!",
  name: "Founders Token",
  address:"0xf11cD86667A5a16E1a9d4971c9a518f3d447b8f3",
  collecionOwner: "0x365e82adAD2C86D38Bec033be04768c8eCd108e4",
  royalty: 0,
  addressShort:"0x10fa5F...",
  category:"Collectibles",
  website:"https://darkmatterdefi.com",
  discord:"VWFVkEfACd",
  twitter:"darkmatterdefi",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/boxedgen.jpg",
  collectionBanner:"/img/banners/unboxedgen.jpg",
  collectionDescription:"The Dark Matter Generals are clashing for total control over Black Holes! The Unboxed Generals served as a test run for our Boxed Generals Series. Now you can enjoy your Unboxed General and passively earn from the Staking Pool!",
  name: "Unboxed Generals",
  address:"0x2dF7E6537BefB7730e790143e2558945e9538fC2",
  collecionOwner: "0x365e82adAD2C86D38Bec033be04768c8eCd108e4",
  royalty: 0,
  addressShort:"0x2dF7E6...",
  category:"Collectibles",
  website:"https://darkmatterdefi.com",
  discord:"VWFVkEfACd",
  twitter:"darkmatterdefi",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ftmfoxboy.jpg",
  collectionBanner:"/img/banners/ftmfoxboy.jpg",
  collectionDescription:"4,444 algorithmically generated fox boys bringing fortune and health into the challenging world full of uncertainties.",
  name: "Fantom Fox Boy",
  address:"0x68b714ac6913b9497817c03ac14cf99bbfb9d737",
  collecionOwner: "0xAAda967a7Fd2A706aFbB32ac8bA5312C868b091e",
  royalty: 6,
  addressShort:"0x68b714...",
  category:"Art & Photography",
  website:"https://visionaryboy.com/fantom-fox-boy",
  discord:"g92CVDRkbE",
  twitter:"FantomBOYbyVB",
  trending:false,
  audit:"Not Audited",
  minting:true,
sellable:true,
  price:"6",
  maxSupply:"4444",
},
{
  image:"/img/collectionmain/autocolor.jpg",
  collectionBanner:"/img/banners/autocolor.jpg",
  collectionDescription:"Made and randomized by human algorithm",
  name: "AUTOCOLOR Technica",
  address:"0xA20E5236B810790F87382D29F11c86C6b68c9b06",
  collecionOwner: "0xd39dbe371B3c839bDCC17c8831eA4706F898E546",
  royalty: 6,
  addressShort:"0xA20E52...",
  category:"Art & Photography",
  website:"https://www.velesero.com",
  discord:"FWAbKhBU3v",
  twitter:"NFT_AUTOCOLOR",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/slothtopiapix.jpg",
  collectionBanner:"/img/banners/slothtopiapix.jpg",
  collectionDescription:"866 Slothtopians living on the Fantom blockchain",
  name: "Slothtopia",
  address:"0x3f5f45138a988f1b32b0f6bcd1cbaa7bcd3c5c0f",
  collecionOwner: "0x5c25f3e763d567e7cbD791141f645D86Dd11c437",
  royalty: 7,
  addressShort:"0x3f5f45...",
  category:"Art & Photography",
  website:"https://www.slothtopia.io/",
  discord:"BjxmSBfJQx",
  twitter:"slothtopianft",
  trending:false,
  audit:"Not Audited",
  minting:false,
sellable:true,
},
{
  image:"/img/collectionmain/ftmpillsog.jpg",
  collectionBanner:"/img/banners/ftmpillsog.jpg",
  collectionDescription:"Fantom Pills is a project about music and harm reduction. Our goal is to make a community to learn and create together. The OG's Edition gives to its holders access to airdrops of all upcoming collections.",
  name: "Fantom Pills OG's Edition",
  address:"0xD02e21b143df16058b9D65d47546a33d1b312b90",
  collecionOwner: "0x1943266B8ddC54c3AD3ca7274D6c6560B41fe5c1",
  royalty: 2,
  addressShort:"0xD02e21...",
  category:"Collectibles",
  website:"https://mint.fantompills.club",
  discord:"JBdFWuxD93",
  twitter:"fantompills",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"15",
  maxSupply:"550",
  sellable:false,
},
{
  image:"/img/collectionmain/cryptoman.jpg",
  collectionBanner:"/img/banners/cryptoman.jpg",
  collectionDescription:"3.000 unique NFTs of CryptoMan for only 2FTM our other collections will be airdropped to holders of CryptoMan.",
  name: "CryptoMan",
  address:"0x31e1fd82b20cc56c2f41a56b2bcdcfda0470aaf9",
  collecionOwner: "0x6341948Cf6A2EeDBdcf43eb0552abe450e336d66",
  royalty: 0,
  addressShort:"0x31e1fd...",
  category:"Collectibles",
  website:"https://www.cryptomanftm.com",
  discord:"",
  twitter:"cryptomanftm",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"2",
  maxSupply:"3333",
  sellable:true,
},
{
  image:"/img/collectionmain/slothtopiaavatar.jpg",
  collectionBanner:"/img/banners/slothtopiaavatar.jpg",
  collectionDescription:"(WARNING: 3D Avatar Collection. Scroll Slowly) 1466 Slothtopians living on the Fantom Blockchain. These sloths are ready to travel across chains and other worlds",
  name: "Slothtopia Avatars",
  address:"0x130710B4Fd678Ede793423374041De1052c724Cf",
  collecionOwner: "0xeB29E0d15c8dc04974Aa74e1BA58eF38d862AEF9",
  royalty: 7,
  addressShort:"0x130710...",
  category:"Games & Virtual Worlds",
  website:"https://www.slothtopia.io/",
  discord:"BjxmSBfJQx",
  twitter:"slothtopianft",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"50",
  maxSupply:"1466",
  sellable:false,
  replacement: true,
  replacementPrefix: 'slothtopiapng/Slothtopia_',
  replacementSubfix: '.png'
},
{
  image:"/img/collectionmain/daemonpunks.jpg",
  collectionBanner:"/img/banners/daemonpunks.jpg",
  collectionDescription:"DaemonPunks are a collection of 345 punks corrupted by the remnant subroutines of the lost BitDaemons. All handmade, all 1/1. Minted on the Fantom blockchain.",
  name: "DaemonPunks",
  address:"0x22DEa64A0e9ecbB13d2B0dD2d95a91A06DACb23B",
  collecionOwner: "0x44f750eB065596c150B3479B1DF6957da300a332",
  royalty: 5,
  addressShort:"0x22DEa6...",
  category:"Collectibles",
  website:"https://bitdaemons.space",
  discord:"h2wEqVgpBD",
  twitter:"DaemonPunks",
  trending:false,
  audit:"Not Audited",
  minting:false,
  price:"0",
  maxSupply:"345",
  sellable:true,
},
{
  image:"/img/collectionmain/funkytiger.jpg",
  collectionBanner:"/img/banners/funkytiger.jpg",
  collectionDescription:"A mob of 2,500 randomly generated Funky Tigers living on the Fantom blockchain!",
  name: "Funky Tiger Mob",
  address:"0xA3034DbEbB9826f6390FA4418417fca43A3B9a87",
  collecionOwner: "0x6F89ea7e96CC7B4d3BaDa29F85dB08bca5B117bc",
  royalty: 5,
  addressShort:"0xA3034D...",
  category:"Collectibles",
  website:"https://funkytigermob.com",
  discord:"4Eygt8dESg",
  twitter:"FunkyTigerMob",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"20",
  maxSupply:"2500",
  sellable:true,
},
{
  image:"/img/collectionmain/fantomgates.jpg",
  collectionBanner:"/img/banners/fantomgates.jpg",
  collectionDescription:"A Spectacular NFT collection, from tight AI-Human collaboration. 1900 Gates to other worlds, through time and space.",
  name: "FantomGates",
  address:"0xf49a2a81C201809eFe99E01D3302fBdd51bb6671",
  collecionOwner: "0x4749532f389487297cDa9308B5b8449E50d4769B",
  royalty: 7.5,
  addressShort:"0xf49a2a...",
  category:"Games & Virtual Worlds",
  website:"https://fantomgates.fantomized.art",
  discord:"cEBMSaz34Y",
  twitter:"fantomized_nfts",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"45",
  maxSupply:"1900",
  sellable:true,
},
{
  image:"/img/collectionmain/neonghosts.jpg",
  collectionBanner:"/img/banners/neonghosts.jpg",
  collectionDescription:"The Neon Ghosts is a collection of 379 friendly spectral entities that haunt the FTM blockchain. They are very special entities, connecting different worlds together and sending positive vibes of different kind to their owner. NeonGhosts come in different flavors, energy or sensibility for instance. Adopt one and benefit from its positive vibes! They come with batteries and advanced features for future uses.",
  name: "NeonGhosts",
  address:"0x749e21C6877CC6bD09f9840d9312295e70A3D3fe",
  collecionOwner: "0x4749532f389487297cDa9308B5b8449E50d4769B",
  royalty: 7.5,
  addressShort:"0x749e21...",
  category:"Collectibles",
  website:"https://neonghosts.fantomized.art",
  discord:"cEBMSaz34Y",
  twitter:"fantomized_nfts",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"50",
  maxSupply:"379",
  sellable:true,
},
{
  image:"/img/collectionmain/s2aliens.jpg",
  collectionBanner:"/img/banners/s2aliens.jpg",
  collectionDescription:"Now you can see yourself and how you would look in the Dark Matter Universe! The Generative NFT Soldiers have varying staking ability power and can earn more from the Pools, find out how strong you are!",
  name: "Series 2 – Aliens",
  address:"0x6f0F3a583d525129B2Fe2F6b7610d516F2d6abb5",
  collecionOwner: "0x365e82adAD2C86D38Bec033be04768c8eCd108e4",
  royalty: 0,
  addressShort:"0x6f0F3a...",
  category:"Collectibles",
  website:"https://darkmatterdefi.com",
  discord:"VWFVkEfACd",
  twitter:"darkmatterdefi",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"25",
  maxSupply:"3000",
  sellable:true,
},
{
  image:"/img/collectionmain/thefantoms.jpg",
  collectionBanner:"/img/banners/thefantoms.jpg",
  collectionDescription:"The Fantoms is a NFTs collection of 3333 unique, randomly generated little fantoms roaming through the Fantom blockchain. Featuring a mint with a reflection mechanism, we redistribute 10% of the minting price to our holders ! Plus, all of the 7.5% royalties from the secondary market are also reflected. Please take a look at our roadmap on the website to see what we have planned for the future.",
  name: "The Fantoms",
  address:"0x513268366106E4B191B9c6ec72247a76BB145Cb1",
  collecionOwner: "0xc3A295185cd20619E7F3d1431F366ff07b668782",
  royalty: 7.5,
  addressShort:"0x513268...",
  category:"Collectibles",
  website:"https://thefantoms.art/#",
  discord:"3TxW38B6wK",
  twitter:"TheFantomsNFT",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"50",
  maxSupply:"3333",
  sellable:true,
},
{
  image:"/img/collectionmain/fhfc.jpg",
  collectionBanner:"/img/banners/fhfc.jpg",
  collectionDescription:"The FHFC Boo Lifetime Mint Passes are LTD edition passes that enable participants to get a GA (Guaranteed Allocation) of 25% of all the WL spots available for every FHFC NFT Drop! If you collect all 11 Unique Editions you can chose to claim a MEGA BOO. There will only ever be 100 MEGA BOOs. MEGA BOOS… they can do some Mega Dope Shit. So might be worth trying to create one. We'll release details on what these MEGA BOOS can do later in the projects growth.",
  name: "FHFC | LTD EDITION MINT PASS",
  address:"0x2741a61fa5ff46288ffccfd0c33891251a2657e2",
  collecionOwner: "0x018154B56F55fD2ff015Ac0FC9E0eb07B8f6f7a6",
  royalty: 10,
  addressShort:"0x2741a6...",
  category:"Collectibles",
  website:"",
  discord:"mHV283kwb8",
  twitter:"FHFCNFT",
  trending:false,
  audit:"Not Audited",
  minting:true,
  price:"11",
  maxSupply:"1111",
  sellable:true,
},
{
  image:"/img/collectionmain/plorc.png",
  collectionBanner:"/img/banners/plorc.png",
  collectionDescription:"1500 of the Potluck Realm Orcs ready for battle on the Fantom Network",
  name: "Potluck Realm Orcs",
  address:"0xdc2bc583f45450e6ae271c48c941b10e073380b5",
  collecionOwner: "0xA6F29Ab1Bf8c731Bc99E5CBacDF4F46409BABa49",
  royalty: 6,
  addressShort:"0xdc2bc5...",
  category:"Art & Photography",
  website:"",
  discord:"potluckprotocol",
  twitter:"potlucklabs",
  trending:true,
  audit:"Not Audited",
  minting:false,
  sellable:true,
},
{
  image:"/img/collectionmain/pixelgatorimg.jpg",
  collectionBanner:"/img/banners/pixelgatorbnr.jpg",
  collectionDescription:"Pixel gators is a collection of 4096 NFT Tokens random uniques pixel art wild and hungry Alligators. The collections is randomly generated, based in 100+ traits, making possible more than a billion combinations.",
  name: "Pixel Gators",
  address:"0x65240A2bDB03A1552aA37345a832B4B797dBfe3C",
  collecionOwner: "0xFE5FA846faa4a22E365149C51DbAe19B596a4258",
  royalty: 5,
  addressShort:"0x65240A...",
  category:"Collectibles",
  website:"https://www.pixelgators.art",
  discord:"",
  twitter:"ftmPixelGators",
  audit:"Not Audited",
  minting:true,
  price:"10",
  maxSupply:"4096",
  sellable:true,
},
{
  image:"/img/collectionmain/ftmqweaponselite.jpg",
  collectionBanner:"/img/banners/ftmqweaponseliteb.jpg",
  collectionDescription:"Fantom Quest Weapons Elite is a collection of 400 specially crafted Weapons with boosted stats, unique attributes and new backgrounds.",
  name: "Fantom Quest Weapons Elite",
  address:"0xd3a23803ad952851bdc95b6bbba83ff5f4fff775",
  collecionOwner: "0x0d1e8bf3ac954d1328a1641e06104212041d6948",
  royalty: 7,
  addressShort:"0xd3a238...",
  category:"Collectibles",
  website:"https://www.fantomquest.com",
  discord:"9N9rnPcwUq",
  twitter:"ftmquest",
  audit:"Not Audited",
  minting:false,
  sellable:true,
},
{
  image:"/img/collectionmain/slurpies.jpg",
  collectionBanner:"/img/banners/slurpiesb.jpg",
  collectionDescription:"Slurp, Slurp, Slurp it up, dudes.",
  prefix:"https://api.slurp.wtf:8080/getTokenMetadata/",
  ipfsUri: 'https://operahouse.mypinata.cloud/ipfs/QmNjqRqdKFFTSZygMm3GeVVioeVukFrKe48GQBUAhVmW8g',
  name: "Slurpies by Zaq",
  address:"0xbf2b77b4b3fbbfe1f7a757d1cab4d294fc027ae8",
  collecionOwner: "0xa3De7Cc7fde1B043FC749EB577E14bED03811D4b",
  royalty: 2.5,
  addressShort:"0xbf2b77...",
  category:"Collectibles",
  website:"https://slurp.wtf",
  discord:"slurpdao",
  twitter:"SLURPDAO",
  audit:"Audited ★★★★★",
  minting:true,
  price:"25",
  maxSupply:"3000",
  sellable:true,
},
{
  image:"/img/collectionmain/fatbirds.jpg",
  collectionBanner:"/img/banners/fatbird.jpg",
  collectionDescription:"1000 of the Fattest Birds on the Fantom Network",
  name: "The Fat Birds",
  address:"0x3D0fEb13142fAB9be63276F658C2a1F5Ab2e1b5d",
  collecionOwner: "0x2Cd0d7330B679ebA2B0A1484e774dF6Fd9Efd331",
  royalty: 6,
  addressShort:"0x3D0fEb...",
  category:"Art & Photography",
  website:"",
  discord:"",
  twitter:"nedpeppermint",
  audit:"Not Audited",
  minting:false,
  sellable:true,
},
{
  image:"/img/collectionmain/spiritman.jpg",
  collectionBanner:"/img/banners/spiritmanb.jpg",
  collectionDescription:"Spirit Man is an NFT Art collection that expresses the inner beauty of the spirit of man. It is a figurine abstract art that typifies spirituality. The first work of the NFT Mobs collection.",
  name: "Spirit Man",
  address:"0xB13c77Bd1901A1564C5e50858632AccCf70b6e62",
  collecionOwner: "0xa43d8C3Fb86988A1Ef928E4d22f0ca6967Ea4416",
  royalty: 2.5,
  addressShort:"0xB13c77...",
  category:"Art & Photography",
  website:"https://www.nft-mobs.com",
  discord:"",
  twitter:"emsevens",
  audit:"Not Audited",
  minting:false,
  sellable:true,
},
{
  image:"/img/collectionmain/cryptodach.jpg",
  collectionBanner:"/img/banners/cryptodachb.jpg",
  collectionDescription:"These are dachshunds. Crypto dachshunds. Cheeky dogs that will conquer your hearts!",
  name: "Crypto Dachshund",
  address:"0x30D1B2161285cbe074962071Af2915C6Bf539642",
  collecionOwner: "0xD3aCf352D27B64064857E916C5e78dECcbb0716d",
  royalty: 3,
  addressShort:"0x30D1B2...",
  category:"Collectibles",
  website:"https://www.instagram.com/badger_warriornft",
  discord:"",
  twitter:"crypto_doxie",
  audit:"Not Audited",
  minting:false,
  sellable:true,
},
{
  image:"/img/collectionmain/coolpenguins.jpg",
  collectionBanner:"/img/banners/coolpenguinsb.jpg",
  collectionDescription:"Cool Penguin Igloo Club is a Club dedicated to bringing the most exclusive utilities to their members.  Cool Penguins will each have a 2D model allowing any pixelated metaverse to accept them walking there. Our vision is to build Igloo Club's all around Fantom metaverses and give our Penguins the ability to go wherever they want and have a home there, could it be cooler? A discord exclusive to holders will arise after mint out to discuss the possibilities for the future of the brand. Grab one to become a member of the Club.",
  name: "Cool Penguin Igloo Club",
  address:"0x2bba27fabc4f009eb7f62d19022a7216166ca69f",
  collecionOwner: "0xF17c3800387A8b91615DE90ef01377ab8E226B6D",
  royalty: 4.5,
  addressShort:"0x2bba27...",
  category:"Collectibles",
  website:"https://coolpenguiniglooclub.com",
  discord:"",
  twitter:"CoolPenguinIC",
  audit:"Not Audited",
  minting:true,  
  price:"1",
  maxSupply:"10000",
  sellable:true,
},
        ]
      };

      // export const getCollectionsByChain = (chain) => networkCollections[chain];
